version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  rest:
    build: .
    command: ./bin/rest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_DSN: postgres://user:pass@db:5432/orders_db?sslmode=disable
  grpc:
    build: .
    command: ./bin/grpc
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      DB_DSN: postgres://user:pass@db:5432/orders_db?sslmode=disable
  graphql:
    build: .
    command: ./bin/graphql
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      DB_DSN: postgres://user:pass@db:5432/orders_db?sslmode=disable